  version: "2"

  services:
    frontend:
      image: nginx
      ports:
        - "80:80"
      environment:
        - GET_HOSTS_FROM=dns
      labels:
        kompose.service.type: LoadBalancer
